metadata:
  backend:
    name: backend
    labels:
      media-project: backend
  staticServer:
    name: static-server-dep
    labels:
      moj: staticniServer

containers:
  backend:
    name: backend-container
    image: backend-svc
  worker:
    name: worker
    image: media-worker
  staticServer:
    name: static-server
    image: static-server

ports:
  backend: 8081
  worker: 8090
  staticServer: 8080

replicas:
  backend: 1
  worker: 1
  staticServer: 1

resources:
  backend:
    limits:
      memory: 500Mi
  worker:
    limits:
      memory: 700Mi
  staticServer:
    limits:
      memory: 300Mi

namespaces:
  kafka: kafka
  backend: media-app
  minio: minio

kafka:
  partitions: 3
  replicas: 1
  retention:
    pending: 600000
    finished: 600000
    canceled: 240000


enable:
  ingress: true
  workers: false
  backend: true
  kafka: false