metadata:
  backend:
    name: backend
    labels:
      media-project: backend
  staticServer:
    name: static-server-dep
    labels:
      moj: staticniServer

secrets:
  mysql:
    connectionString: jdbc:mysql://host.docker.internal:3306/media
    username: root
    password: sigurnost
  minio:
    endpoint: host.docker.internal #my-minio.minio.svc.cluster.local
    port: 9000
    accessKey: WuKQ7RStEM9tmVw4
    secret: RXN9tTl28xQ7a9j15scfo5qGoqO5mfSv

containers:
  backend:
    name: backend-container
    image: backend-img
  worker:
    name: worker
    image: worker-img
  staticServer:
    name: static-server
    image: static-server-img

ports:
  backend: 8081
  worker: 8090
  staticServer: 80

replicas:
  backend: 1
  worker: 2
  staticServer: 1
  zookeeper: 1
  kafka: 1

resources:
  backend:
    limits:
      memory: 500Mi
  worker:
    limits:
      memory: 700Mi
  staticServer:
    limits:
      memory: 300Mi
  kafka:
    diskSize: 6Gi

namespaces:
  backend: media-app
  minio: object-storage
  kafka: kafka

kafka:
  partitions: 2
  replicas: 1
  retention:
    pending: 600000
    notifications: 300000
    canceled: 300000

enable:
  ingress: true
  workers: true
  backend: true
  kafka: true

strimzi-kafka-operator:
  watchAnyNamespace: true