apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespaces.backend }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.ports.backend }}
  selector:
    {{- toYaml .Values.metadata.backend.labels | nindent 4 }}